controllers:
    resource: ../src/FantasyVerse/Controller/
    type: attribute


#

home:
    path: /
    controller: Fv\FantasyVerse\Controller\GetHomeController
    methods: GET

landing:
    path: /landing
    controller: Fv\FantasyVerse\Controller\LandingController
    methods: GET


perfil_usuario:
    path: /perfil_usuario
    controller: Fv\FantasyVerse\Controller\PerfilUsuarioController::perfil





ver_personajes:
    path: /personajes
    controller: Fv\FantasyVerse\Controller\PersonajeController

editar_personaje:
    path: /personaje/editar/{id}
    controller: Fv\FantasyVerse\Controller\PersonajeController::editarPersonaje

guardar_personaje:
    path: /personaje/guardar/{id}
    controller: Fv\FantasyVerse\Controller\PersonajeController::guardarPersonaje
    methods: [POST]




campanyas:
    path: /campañas
    controller: Fv\FantasyVerse\Controller\CampañasController::index

eventos:
    path: /eventos
    controller: Fv\FantasyVerse\Controller\EventosController::index

perfil:
    path: /perfil
    controller: Fv\FantasyVerse\Controller\PerfilController::index


usuario_index:
    path: /usuarios
    controller: Fv\FantasyVerse\Controller\UsuarioController::index


ruta_admin:
    path: /admin
    controller: Fv\FantasyVerse\Controller\AdminController::index

ruta_usuario:
    path: /usuario
    controller: Fv\FantasyVerse\Controller\UsuarioController

ruta_invitado:
    path: /invitado
    controller: Fv\FantasyVerse\Controller\InvitadoController::index

logout:
    path: /logout
