controllers:
    resource: ../src/Controller/
    type: attribute


#

home:
    path: /
    controller: Fv\Controller\GetHomeController
    methods: GET

landing:
    path: /landing_prueba
    controller: Fv\Controller\LandingController::index 
    methods: GET





ver_personaje_prueba:
    path: /personaje_prueba
    controller: Fv\Controller\PersonajePruebaController

ver_personajes:
    path: /personajes
    controller: Fv\Controller\PersonajeController

editar_personaje:
    path: /personaje/editar/{id}
    controller: Fv\Controller\PersonajeController::editarPersonaje

guardar_personaje:
    path: /personaje/guardar/{id}
    controller: Fv\Controller\PersonajeController::guardarPersonaje
    methods: [POST]




campanyas:
    path: /campañas
    controller: Fv\Controller\CampañasController::index

eventos:
    path: /eventos
    controller: Fv\Controller\EventosController::index

perfil:
    path: /perfil
    controller: Fv\Controller\PerfilController::index


usuario_index:
    path: /usuarios
    controller: Fv\Controller\UsuarioController::index


ruta_admin:
    path: /admin
    controller: Fv\Controller\AdminController::index

ruta_usuario:
    path: /usuario
    controller: Fv\Controller\UsuarioController

ruta_invitado:
    path: /invitado
    controller: Fv\Controller\InvitadoController::index

logout:
    path: /logout
