prueba:
    path: /prueba
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template: "views/prueba.html.twig"
    
home:
    path: /
    controller: Fv\Controller\GetHomeController
    methods: GET