security:
    password_hashers:
        Fv\FantasyVerse\Entity\Usuario:
            algorithm: auto

    providers:
        usuarios:
            entity:
                class: Fv\FantasyVerse\Entity\Usuario
                property: correo

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: usuarios
            form_login:
                login_path: login
                check_path: login
                success_handler: Fv\FantasyVerse\Security\RedireccionPorRol
                enable_csrf: true
            logout:
                path: logout
                target: /login
            
                

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/usuario, roles: ROLE_USER }
        - { path: ^/invitado, roles: ROLE_INVITADO }
        - { path: ^/login, roles: PUBLIC_ACCESS }

        - { path: ^/personaje, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/campanyas, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/eventos, roles: [ROLE_USER, ROLE_ADMIN]}




